export const ErrorConstants = {
  names: {
    TEST_ERROR: 'TEST_ERROR',
    LLM_REQUEST_ERROR: 'LLM_REQUEST_ERROR',
    CONSTRAINT_VALIDATION_ERROR: 'CONSTRAINT_VALIDATION_ERROR',
    ILLEGAL_ARGUMENT_ERROR: 'ILLEGAL_ARGUMENT_ERROR',
    COULDNT_GET_NEWS_RESPONSE_ERROR: 'COULDNT_GET_NEWS_RESPONSE_ERROR',
    MALFORMED_NEWS_REQUEST_ERROR: 'MALFORMED_NEWS_REQUEST_ERROR',
    UNAUTHORIZED_NEWS_REQUEST_ERROR: 'UNAUTHORIZED_NEWS_REQUEST_ERROR',
    TOO_MANY_NEWS_REQUEST_ERROR: 'TOO_MANY_NEWS_REQUEST_ERROR',
    EMPTY_NEWS_REQUEST_RESPONSE_ERROR: 'EMPTY_NEWS_REQUEST_RESPONSE_ERROR',
    COULDNT_RETRIEVE_PROMPT_TEMPLATE_ERROR: 'COULDNT_RETRIEVE_PROMPT_TEMPLATE_ERROR',
    COULDNT_SEND_EMAIL_ERROR: 'COULDNT_SEND_EMAIL_ERROR',
  },
};
